<script setup lang="ts">
import { ref } from 'vue';
import './assets/css/index.css';
import Toaster from '@/components/ui/toast/Toaster.vue';
import { Sidebar } from '@/components/sidebar';
import {
	ResizableHandle,
	ResizablePanel,
	ResizablePanelGroup,
} from '@/components/ui/resizable';
import {
	AlertDialog,
	AlertDialogAction,
	AlertDialogCancel,
	AlertDialogContent,
	AlertDialogDescription,
	AlertDialogFooter,
	AlertDialogHeader,
	AlertDialogTitle,
	AlertDialogTrigger,
} from '@/components/ui/alert-dialog';
import useElectron from '@/composables/useElectron';
import { useColorMode } from '@vueuse/core';
import { isDevMode } from '@/lib/utils';

useColorMode();

const { toggleDevTools, closeApp } = useElectron();

const enteredApp = ref(true);

(window as any).latestAppKeyDownHandlerId = Math.random();
const handleAppKeyDown = ((id) => async (e: KeyboardEvent) => {
	if (!toggleDevTools) return console.error('useElectron not available');
	if (id !== (window as any).latestAppKeyDownHandlerId) return;

	const key = e.key.toLowerCase();

	const holdingCtrl = e.metaKey || e.ctrlKey;
	const holdingShift = e.altKey || e.shiftKey;

	if (key === 'r' && holdingCtrl && !holdingShift) {
		e.preventDefault();
		window.location.reload();
	} else if (key === 'i' && holdingCtrl && holdingShift && !isDevMode()) {
		e.preventDefault();
		toggleDevTools();
	}
})((window as any).latestAppKeyDownHandlerId);

window.addEventListener('keydown', handleAppKeyDown);

const doCloseApp = () => {
	enteredApp.value = false;
	if (closeApp) closeApp();
};

const container = ref<HTMLElement | null>(null);
</script>

<template>
	<div
		ref="container"
		class="antialiased duration-300 transition-colors text-gray-800 dark:text-gray-200 bg-white dark:bg-gray-950"
	>
		<Suspense v-if="enteredApp">
			<ResizablePanelGroup direction="horizontal">
				<ResizablePanel
					class="min-w-min"
					:default-size="22"
					:min-size="20"
					:max-size="35"
				>
					<Sidebar />
				</ResizablePanel>
				<ResizableHandle with-handle />
				<ResizablePanel>
					<RouterView />
				</ResizablePanel>
			</ResizablePanelGroup>
		</Suspense>
		<AlertDialog :open="!enteredApp">
			<AlertDialogContent :portal-to="container">
				<AlertDialogHeader>
					<AlertDialogTitle>Adults Only</AlertDialogTitle>
					<AlertDialogDescription>
						This game uses content generated by AI based on what you input. There may
						be unexpected reults.
						<br />
						Use your best judgement and be responsible with the content that you
						create with the game.
						<br />
						<b class="text-lg py-1">Are you 18 years or older?</b>
					</AlertDialogDescription>
				</AlertDialogHeader>
				<AlertDialogFooter>
					<AlertDialogCancel @click="doCloseApp"> No / Exit </AlertDialogCancel>
					<AlertDialogAction @click="enteredApp = true">
						Yes / Enter
					</AlertDialogAction>
				</AlertDialogFooter>
			</AlertDialogContent>
		</AlertDialog>
		<Toaster />
	</div>
</template>

<style>
html,
body {
	@apply h-screen w-screen overflow-y-hidden;
}
.info {
	@apply bg-blue-400 text-white font-bold;
}
.border-info {
	@apply border-blue-700;
}
.info-foreground {
	@apply text-blue-400 bg-white;
}

.success {
	@apply bg-green-400 text-black font-bold;
}
.border-success {
	@apply border-green-700;
}
.success-foreground {
	@apply text-green-400 bg-white;
}

.magic {
	@apply bg-purple-400 text-black font-bold;
}
</style>
