/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/auth/callback': RouteRecordInfo<'/auth/callback', '/auth/callback', Record<never, never>, Record<never, never>>,
    '/buddy/[id]/edit': RouteRecordInfo<'/buddy/[id]/edit', '/buddy/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/buddy/[id]/history': RouteRecordInfo<'/buddy/[id]/history', '/buddy/:id/history', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/buddy/[id]/view': RouteRecordInfo<'/buddy/[id]/view', '/buddy/:id/view', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/chat/[id]': RouteRecordInfo<'/chat/[id]', '/chat/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/create-buddy': RouteRecordInfo<'/create-buddy', '/create-buddy', Record<never, never>, Record<never, never>>,
    '/credits': RouteRecordInfo<'/credits', '/credits', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/auth/callback.vue': {
      routes: '/auth/callback'
      views: never
    }
    'src/pages/buddy/[id]/edit.vue': {
      routes: '/buddy/[id]/edit'
      views: never
    }
    'src/pages/buddy/[id]/history.vue': {
      routes: '/buddy/[id]/history'
      views: never
    }
    'src/pages/buddy/[id]/view.vue': {
      routes: '/buddy/[id]/view'
      views: never
    }
    'src/pages/chat/[id].vue': {
      routes: '/chat/[id]'
      views: never
    }
    'src/pages/create-buddy.vue': {
      routes: '/create-buddy'
      views: never
    }
    'src/pages/credits.vue': {
      routes: '/credits'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
