/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/chat/[id]': RouteRecordInfo<'/chat/[id]', '/chat/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/create-buddy': RouteRecordInfo<'/create-buddy', '/create-buddy', Record<never, never>, Record<never, never>>,
    '/credits': RouteRecordInfo<'/credits', '/credits', Record<never, never>, Record<never, never>>,
    '/persona/[id]/edit': RouteRecordInfo<'/persona/[id]/edit', '/persona/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/persona/[id]/history': RouteRecordInfo<'/persona/[id]/history', '/persona/:id/history', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/persona/[id]/view': RouteRecordInfo<'/persona/[id]/view', '/persona/:id/view', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }
}
