name: Deploy Docs

on:
 push:
  branches:
   - spa-version
  paths:
   - '.github/workflows/deploy-docs.yml'
   - 'docs/**'

permissions:
  contents: read
jobs:
 build-deploy:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v3
   - uses: actions/setup-node@v3
     with:
      node-version: 18
   - run: npm ci
   - run: npm run docs:build
   - name: Deploy to Pages
     uses: peaceiris/actions-gh-pages@v3
     with:
      personal_token: ${{ secrets.DEPLOY_TOKEN }}
      external_repository: parsehex/buddygenai-docs
      publish_branch: gh-pages
      publish_dir: ./docs/.vitepress/dist
      cname: docs.buddygenai.com
